language: php

sudo: false
dist: trusty

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

stages:
  - check
  - test

matrix:
  fast_finish: true

jobs:
  include:
    - stage: check
      language: php
      php: '7.2'
      script: bash tests/bin/php/phpcs.sh
    - stage: check
      language: php
      php: '7.2'
      script: bash tests/bin/php/phpmd.sh

    - stage: check
      language: node_js
      node_js: '11'
      dist: trusty
      script: bash tests/bin/js/js-lint.sh


    - stage: test
      language: php
      php: '7.3'
      env:
        - WP_VERSION=latest
        - COVERAGE_REPORT=1
      script: bash tests/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.3'
      env:
        - WP_VERSION=latest
        - WP_MULTISITE=1
        - COVERAGE_REPORT=1
      script: bash tests/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.2'
      env: WP_VERSION=latest
      script: bash tests/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.2'
      env:
        - WP_VERSION=5.2
        - WP_MULTISITE=1
      script: bash tests/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.1'
      env: WP_VERSION=latest
      script: bash tests/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.1'
      env:
        - WP_VERSION=5.1
        - WP_MULTISITE=1
      script: bash tests/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.0'
      env:
        - WP_VERSION=latest
        - COVERAGE_REPORT=1
      script: bash tests/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '7.0'
      env:
        - WP_VERSION=5.0
        - WP_MULTISITE=1
      script: bash tests/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env: WP_VERSION=latest
      script: bash tests/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env:
        - WP_VERSION=5.0
        - WP_MULTISITE=1
        - COVERAGE_REPORT=1
      script: bash tests/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env: WP_VERSION=trunk
      script: bash tests/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env: WP_VERSION=4.9
      script: bash tests/bin/php/wp-test.sh
    - stage: test
      language: php
      php: '5.6'
      env: WP_VERSION=3.9
      script: bash tests/bin/php/wp-test.sh

    - stage: test
      language: node_js
      node_js: '10'
      dist: trusty
      script: bash tests/bin/js/js-test.sh
    - stage: test
      language: node_js
      node_js: '11'
      dist: trusty
      env: COVERAGE_REPORT=1
      script: bash tests/bin/js/js-test.sh

  allow_failures:
    - env: WP_VERSION=4.9
    - env: WP_VERSION=3.9
