language: php

sudo: false
dist: trusty

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

stages:
  - check_wp
  - check_js
  - test_wp
  - test_js
  - report

jobs:
  include:
    - stage: check_wp
      language: php
      php: '5.6'
      script: bash tests/bin/php/phpcs.sh
    - stage: check_wp
      language: php
      php: '5.6'
      script: bash tests/bin/php/phpmd.sh

    - stage: check_js
      language: node_js
      node_js: '11'
      dist: trusty
      script: bash tests/bin/js/js-lint.sh

    - stage: test_wp
      language: php
      php: '7.3'
      env: WP_VERSION=latest
      script: bash tests/bin/php/wp-test.sh
    - stage: test_wp
      language: php
      php: '7.3'
      env:
        - WP_VERSION=latest
        - WP_MULTISITE=1
      script: bash tests/bin/php/wp-test.sh
    - stage: test_wp
      language: php
      php: '7.2'
      env: WP_VERSION=latest
      script: bash tests/bin/php/wp-test.sh
    - stage: test_wp
      language: php
      php: '7.2'
      env:
        - WP_VERSION=5.2
        - WP_MULTISITE=1
      script: bash tests/bin/php/wp-test.sh
    - stage: test_wp
      language: php
      php: '7.1'
      env: WP_VERSION=latest
      script: bash tests/bin/php/wp-test.sh
    - stage: test_wp
      language: php
      php: '7.1'
      env:
        - WP_VERSION=5.1
        - WP_MULTISITE=1
      script: bash tests/bin/php/wp-test.sh
    - stage: test_wp
      language: php
      php: '7.0'
      env: WP_VERSION=latest
      script: bash tests/bin/php/wp-test.sh
    - stage: test_wp
      language: php
      php: '7.0'
      env:
        - WP_VERSION=5.0
        - WP_MULTISITE=1
      script: bash tests/bin/php/wp-test.sh
    - stage: test_wp
      language: php
      php: '5.6'
      env: WP_VERSION=latest
      script: bash tests/bin/php/wp-test.sh
    - stage: test_wp
      language: php
      php: '5.6'
      env:
        - WP_VERSION=5.0
        - WP_MULTISITE=1
      script: bash tests/bin/php/wp-test.sh
    - stage: test_wp
      language: php
      php: '5.6'
      env: WP_VERSION=trunk
      script: bash tests/bin/php/wp-test.sh
    - stage: test_wp
      language: php
      php: '5.3'
      env: WP_VERSION=latest
      dist: precise
      script: bash tests/bin/php/wp-test.sh
    - stage: test_wp
      language: php
      php: '5.2'
      env: WP_VERSION=3.9
      dist: precise
      script: bash tests/bin/php/wp-test.sh
    - stage: test_wp
      language: php
      php: 'hhvm'
      env: WP_VERSION=latest
      script: bash tests/bin/php/wp-test.sh

    - stage: test_js
      language: node_js
      node_js: '11'
      dist: trusty
      script: bash tests/bin/js/js-test.sh

    - stage: report
      language: php
      php: '5.6'
      script: bash tests/bin/report.sh
